# Crie um Dockerfile utilizando a imagem chuanwen/cowsay.
FROM chuanwen/cowsay:latest

# Agora defina um ENTRYPOINT para a execução do comando.
# Lembre-se que com ele, diferente do CMD o comando não poderá ser sobrescrito com o docker run, porém, #  conseguiremos passar parâmetros ao binário, exploraremos esse recurso para poder passar a mensagem.
ENTRYPOINT [ "/usr/games/cowsay" ]

# Utilize o CMD para definir uma mensagem padrão.
CMD [ "#VQV Trybe" ]

# Builde e execute um container baseado em sua imagem sem passar nenhum comando.

